- .github/PULL_REQUEST_TEMPLATE.md
Adding templates to our Repo when we open pull requests!
> feat: adding PR template

- client/i18n/config.ts
Giving default language `en` if localStorage not set for Multilingual Support
> fix: multilingual bug

- client/pages/NewForm/NewForm.tsx
- server/app.js
- server/controllers/form.controller.js
- server/migrations/20240608203625-create-form.js
- server/models/form.js
- server/models/group.js
- server/mongoModels/form.js
- server/mongoModels/raw_response.js
- server/mongoModels/response.js
- server/mongoModels/response_id.js
- server/mongodb.js
- server/routes/form.routes.js
- server/utilityFunctions/responseParser.js
- mongoose schemas/models stored in the `mongoModels` 
- new form routes and controller file 
- this is a cleaner version from @JesusGo115  original pr #70 (we will now close this one, once this is approved)
- Mongoose setup , Schema and controller logic worked by @garcialuis,  @JesusGo115 , @villaleo  and myself.
> Feature/ Form  GET and POST Routes 

- server/controllers/form.controller.js
- server/routes/form.routes.js
- new form endpoint in the controller file
> feat: Added the getForm Endpoint to the Form Controller

- client/api/forms/service.ts
- server/routes/form.routes.js
Fixed getting all the forms and made it RESTful
> fix: Made getting all forms RESTful

- server/controllers/division.controller.js
- server/routes/season.routes.js
Added a new endpoint to get Division data by Season ID
> Feat: Get Division by Season ID

- client/components/FormResponses/FormResponses.tsx
- server/routes/season.routes.js
Fixed an issue that prevented responses from being displayed
> Response Display Issue Fix

- client/api/users/service.ts
- client/components/SelectMenu/SelectMenu.module.css
- client/components/SelectMenu/SelectMenu.tsx
- client/pages/Register/OrganizationFields.tsx
- client/pages/Register/PersonalInfoFields.tsx
- client/pages/Register/Register.module.css
- client/pages/Register/Register.tsx
- client/pages/Register/states.json
- client/pages/Routes.tsx
Made changes to the Register UI
N/A
> feat: Updated UI for Register

- client/components/RegistrationModal/RegistrationModal.tsx
- client/pages/Home/Home.tsx
- client/pages/Routes.tsx
POC for registration modal popup immediately after creating account and first logging in!
> feat: auth0 register redirection with persistent modal

- server/README.md
- server/config/README.md
- server/controllers/README.md
- server/models/README.md
- server/routes/README.md
This PR introduces detailed documentation for the server folder, including:
- Configuration overview
- Routes documentation with endpoint tables
- Controllers summary
- Models directory explanation
- Middleware documentation
These additions will improve developer onboarding and provide a clear overview of the server-side architecture.
> doc: add comprehensive documentation for server components

- .github/workflows/publish.yml
- create-env.js
> fix: build images with workflow

- client/src/api/forms/types.ts
- client/src/components/FormInputComponents/Dropdown/Dropdown.tsx
- client/src/components/FormInputComponents/LongText/LongText.tsx
- client/src/components/FormInputComponents/ShortText/ShortText.tsx
- client/src/components/FormResponses/FormResponses.tsx
- client/src/components/ProgressBar/ProgressBar.tsx
- client/src/pages/FormPage/FormPage.module.css
- client/src/pages/FormPage/FormPage.tsx
- client/src/pages/FormPage/types.ts
Working to add typeform like form experience based on [existing web app demo](https://cascarita-io.github.io/registration-form/). Mobile friendly as well!
https://cascarita.atlassian.net/browse/CV-3
> feat: adding typeform-like experience to survey

- client/src/components/DragAndDropComponents/DraggablePlayer/DraggablePlayer.tsx
> fix: fixing eslint build errors

- server/models/formpayment.js
Spelling mistake, model is `User` not `Users`
> Fix: FormPayment model breaking Server

- client/src/@types/resources.ts
- client/src/api/users/mutations.ts
- client/src/api/users/service.ts
- client/src/components/Forms/PlayerForm/PlayerForm.module.css
- client/src/components/Forms/PlayerForm/PlayerForm.tsx
- client/src/components/Forms/PlayerForm/types.ts
- client/src/components/Forms/UserForm/types.tsx
- client/src/i18n/config.ts
- client/src/i18n/en/pages/Players.json
- client/src/i18n/esp/pages/Players.json
- client/src/pages/Home/Home.tsx
- client/src/pages/Players/Players.tsx
- client/src/pages/Players/types.ts
- client/src/pages/Routes.tsx
- server/controllers/user.controller.js
- server/migrations/20250217191457-update-user-session-with-team-id-col.js
- server/models/usersessions.js
- server/routes/user.routes.js
Working to create player view tab in Home.
> feat: player tab

- client/src/assets/Icons/BlueCheckMarkIcon.tsx
- client/src/components/Layout/blacklist.ts
- client/src/components/ThankYou/ThankYou.module.css
- client/src/components/ThankYou/ThankYou.tsx
- client/src/pages/FormPage/FormPage.tsx
- client/src/pages/Routes.tsx
Thank you component to be rendered at the end of the form construction workflow
https://cascarita.atlassian.net/browse/CV-66
> feat: thank you component

- client/src/api/users/types.ts
- client/src/components/RegistrationModal/RegistrationModal.tsx
- client/src/components/RegistrationModal/types.ts
- server/controllers/group.controller.js
- server/controllers/user.controller.js
- server/migrations/20250223013158-add-group-code-column.js
- server/models/group.js
Implements unique group codes. These codes are now required and checked by the registration api to ensure that only users with the correct code can join an existing group.
[CV-83](https://cascarita.atlassian.net/browse/CV-83?atlOrigin=eyJpIjoiOTliZDc0Y2ZiNjRmNGFiM2IzNmFkNTkyZmI5ZWI1YjMiLCJwIjoiaiJ9)
> Feat: Unique group codes

- client/src/pages/Players/Players.tsx
- client/src/pages/Teams/Teams.tsx
Updates message displayed when a Team is not linked to a division
> fix: update display message for a team that is not linked  to a division

- server/app.js
- server/controllers/stripeResources/connectedAccount.controller.js
- server/controllers/stripeResources/formTransaction.controller.js
Fix Stripe webhook verification in prod
> fix: adding working changes to stripe in prod

- client/src/components/FormResponses/FormResponses.tsx
- server/app.js
- server/controllers/account.controller.js
Moving middlewares to prevent error
> fix: changes to app.js to re-arrange middleware

- client/package.json
- client/src/api/divisions/mutations.ts
- client/src/api/divisions/service.ts
- client/src/api/leagues/mutations.ts
- client/src/api/leagues/service.ts
- client/src/api/seasons/mutations.ts
- client/src/api/seasons/services.ts
- client/src/api/teams/mutations.ts
- client/src/api/teams/service.ts
- client/src/api/users/mutations.ts
- client/src/api/users/service.ts
- client/src/components/Forms/DivisionForm/DivisionForm.tsx
- client/src/components/Forms/DivisionForm/types.ts
- client/src/components/Forms/LeagueForm/LeagueForm.tsx
- client/src/components/Forms/LeagueForm/schema.ts
- client/src/components/Forms/LeagueForm/types.tsx
- client/src/components/Forms/PlayerForm/PlayerForm.tsx
- client/src/components/Forms/PlayerForm/types.ts
- client/src/components/Forms/SeasonForm/SeasonForm.tsx
- client/src/components/Forms/SeasonForm/schema.ts
- client/src/components/Forms/SeasonForm/types.ts
- client/src/components/Forms/TeamsForm/TeamForm.tsx
- client/src/components/Forms/TeamsForm/types.ts
- client/src/pages/Seasons/Seasons.tsx
- server/controllers/league.controller.js
- server/controllers/season.controller.js
- server/controllers/user.controller.js
When a user creates an account, they will be assigned the role of "Staff" with ID 1.
[Jira Ticket](https://cascarita.atlassian.net/browse/CV-101?atlOrigin=eyJpIjoiNWNjNzg2M2Q2YTMxNDg3M2I1MzdhYmU2NWQzYzUyNjEiLCJwIjoiaiJ9)
> fix: assign role on registration

- server/seeders/20240902193649-demo-stripe-user.js
> update test seed file

- docker-compose.yml
- server/package-lock.json
When running through some merge from main errors with, @jipatino98 and I noticed that `node_modules` of the volume mount (your local machine), were still getting prioritized. Added this extra alias volume mount to out `docker-compose.yml` file that will prioritize the `node_modules` inside the container as per [this blog](https://justinecodez.medium.com/docker-volumes-and-the-node-modules-conundrum-fef34c230225).
> fix: docker compose dev environment

- client/src/api/forms/query.ts
- client/src/api/forms/service.ts
- client/src/components/DragAndDropComponents/DNDCanvas/DNDCanvas.tsx
- client/src/components/DragAndDropComponents/DNDCanvas/types.ts
- client/src/pages/FormPage/FormPage.tsx
- client/src/pages/Forms/Forms.tsx
- client/src/pages/NewForm/NewForm.tsx
- server/routes/form.routes.js
If we create a registration form type, we cannot delete or copy the draggable components from the custom form builder
https://cascarita.atlassian.net/browse/CV-130
> fix: prevent delete payment block

- client/src/index.tsx
- client/vite.config.ts
- server/app.js
When deploying faced some issues along allowedHosts and middleware ordering to not showing sentry reports for backend
> fix: deployment issues

- client/src/components/FormInputComponents/PlayerBlock/PlayerBlock.tsx
- client/src/components/Forms/PlayerForm/PlayerForm.tsx
- client/src/components/Forms/RegistrationTemplateForm/RegistrationTemplateForm.tsx
- client/src/components/Forms/RegistrationTemplateForm/helper.ts
- client/src/components/ProtectedRoute/ProtectedRoute.tsx
- client/src/i18n/en/pages/NewForms.json
- client/src/pages/NewForm/NewForm.tsx
- server/controllers/account.controller.js
1. This pr will [remove platform fees](https://cascarita.atlassian.net/browse/CV-142)
2. update button names ([Back](https://cascarita.atlassian.net/browse/CV-149) , [Save](https://cascarita.atlassian.net/browse/CV-150))
3. [update Free Agent Text](https://cascarita.atlassian.net/browse/CV-147)
4. Fix [redir](https://cascarita.atlassian.net/browse/CV-146) to `/login` 
5. [remove preview form button](https://cascarita.atlassian.net/browse/CV-151)
> Feature: Remove Backend Fees and Misc

- Makefile
Quick PR to just run the script on windows. Windows can't install homebrew, so there might be some more work to do to have the proper environment setup
> feat (Setup): updating script to run on windows

- server/controllers/user.controller.js
- server/routes/user.routes.js
- server/utilityFunctions/createPayerUser.js
This PR adds endpoint that will handle requests made when admins create a new user.
Refactoring had to be done to some of the User Controller to reuse user creation code.
[CV-167](https://cascarita.atlassian.net/browse/CV-167?atlOrigin=eyJpIjoiYjNhODRmY2M1NDkwNGViZjk1ZmY4YjliYjI4NWRhNzkiLCJwIjoiaiJ9)
Expected data in request:
```json
{
"address": "234 Some Address Ave",
"date_of_birth": "2020-12-12",
"division_id": 1,
"email": "email@testdomain.com",
"first_name": "MyFirstName",
"last_name": "MyLastName",
"league_id": 1,
"liability": true,
"link_to_team": "yes",
"phone_number": "1231231234",
"season_id": 1,
"team_id": 748,
"group_id": 3,
"picture": "photoURL"
}
```
> feat: add createUser endpoint

- client/src/components/FileUpload/FileUpload.module.css
- client/src/components/FileUpload/FileUpload.tsx
- client/src/components/FormInputComponents/Photo/Photo.module.css
- client/src/components/FormInputComponents/Photo/Photo.tsx
- client/src/components/Forms/Form.module.css
- client/src/components/Forms/PlayerForm/PlayerForm.tsx
- client/src/components/Forms/PlayerForm/PlayerFormPageThree.tsx
- client/src/components/Forms/PlayerForm/schema.ts
- client/src/components/Forms/PlayerForm/types.ts
- client/src/components/Forms/TeamsForm/TeamForm.tsx
- client/src/components/Header/Header.module.css
- client/src/components/Modal/Modal.module.css
- client/src/components/Page/Page.module.css
- client/src/i18n/en/pages/Players.json
- client/src/pages/Seasons/Seasons.tsx
- server/controllers/user.controller.js
This PR introduces some changes including:
- Adding liability checkmarks for photo and minor player creation in the Player Modal
- Fixing some styling bugs in the mobile view for the Team and Photo block
> fix: Addressed styling bugs in Photo block and Team modal

- client/src/components/DropdownMenuButton/DropdownMenuButton.tsx
- client/src/i18n/en/components/DropdownMenuButton.json
- client/src/i18n/esp/components/DropdownMenuButton.json
- client/src/pages/Forms/Forms.tsx
This PR refactors the dropdown button component. Currently there was a fork in the logic to accommodate forms dropdown menu, this PR fixes that and abstracts Dropdown buttons
> Refactor (Dropdown Button Component): abstracting dropdown menu button and refactoring forms

- server/controllers/form.controller.js
- server/controllers/group.controller.js
- server/controllers/s3.controller.js
- server/models/permissions.js
- server/models/role.js
- server/models/rolePermission.js
- server/routes/s3.routes.js
- server/utilityFunctions/createPayerUser.js
- server/utilityFunctions/paymentIntents.js
This PR updates s3 route and some controllers so that they are ready to go for any role based authorization changes.
> Chore: prepare routes and controllers for roles
