cascarita-io/cascarita

client/assets/CopyIcon.tsx
client/components/DNDCanvas/DNDCanvas.tsx
client/components/DNDCanvas/types.ts
client/components/DraggableDropdown/DraggableDropdown.tsx
client/components/DraggableDropdown/types.ts
client/components/DraggableLongText/DraggableLongText.tsx
client/components/DraggableLongText/types.ts
client/components/DraggableMultipleChoice/DraggableMultipleChoice.tsx
client/components/DraggableMultipleChoice/types.ts
client/components/DraggableShortText/DraggableShortText.tsx
client/components/DraggableShortText/types.ts
client/components/DraggableSubMenu/DraggableSubMenu.tsx
client/components/DraggableSubMenu/types.ts
client/components/DropdownMenuButton/DropdownMenuButton.tsx
client/components/DropdownMenuButton/types.ts
client/components/Page/Page.module.css
client/pages/Forms/Forms.tsx
client/pages/Forms/types.ts
client/pages/Leagues/Leagues.tsx
client/pages/NewForm/NewForm.tsx
server/routes/survey.routes.js

_Had to upload a crappy quality because Github only allows 10MB videos 💀_ 
https://github.com/cascaritaco/cascarita/assets/33636358/2dc95563-5151-409e-ab8d-a917c7150bc8
- Added Copy Feature: Copies draggable elements
- Added Save forms Feature: Saves forms through local storage
- Added TypeForm CRUD feature: Users can update/delete forms and it will update through TypeForm
[Jira Link](https://cascarita.atlassian.net/browse/C1-99)
- Saving forms through local storage is a temp fix until the back-end + database is setup to save and retrieve form data.

Feat (Form Builder): Copy Draggable Elements + Update/Delete Forms 

---

server/utilityFunctions/responseParser.js

Adds a utility function to parse raw responses object into individual responses.
The parsing logic also includes functionality to identify duplicates (responses that have already been parsed in the past).
This utility function will later be used by the endpoint that handles retrieving individual responses and serving it to the client.
You can run the utility function by running `node server/utilityFunctions/responseParser.js`

feat: add utility function to parse raw responses object

---

client/api/forms/service.ts
client/pages/NewForm/NewForm.tsx
jest.setup.js
package-lock.json
package.json
server/controllers/form.controller.js
server/migrations/20240611200740-update-form-sql-table-add-user-columns.js
server/models/form.js
server/models/user.js
server/mongoModels/form.js
server/routes/form.routes.js
server/routes/group.routes.js

- route gets all the forms for a from a group id.
- update the `Forms` sql table to include user id for whoever created the form and whoever updated the form 
- need to delete all your SQL Forms data and run migrations 
- need to delete all mongo db clusters so its all in sync
- one thing to note is that we only looking up existing forms from our SQL `Forms` table , not making a GET request to typeform

Feature: Add GET Form endpoints 

---

client/api/forms/service.ts
client/components/FormResponses/FormResponses.tsx
client/pages/Forms/Forms.tsx
client/pages/Forms/types.ts
client/pages/NewForm/NewForm.tsx
server/routes/form.routes.js

- feat(form routes): Added Mongo API call to get all forms and seperated Typeform Logic from Mongo API calls
- feat(routing): API routes to mongo for fetching forms and forms by id
- feat(responses): Added fetch form fields through our mongo db endpoint
Re-routed some of the typeform calls to our mongo db calls
[Jira Link](https://cascarita.atlassian.net/browse/C1-99)
- **The Backend does need a lot of refactor, as there's a a lot usage of  `Schema.Types.Mixed` being used, and fetching the data is creating a lot of bugs when we don't know what data we're receiving (currently fetching form by id is returning an array instead of the form itself). I do assume these will get changed when we move away from typeform's api calls 😃 .**
- Since we do not have Update/Delete endpoints, the Delete / …

[Feat]: Rerouted Typeform get form(s) endpoints to Mongo DB

---

client/components/FormResponses/FormResponses.tsx
client/components/FormResponses/types.ts
client/pages/Forms/Forms.tsx
client/pages/NewForm/NewForm.tsx
server/controllers/form.controller.js

- feat(responses route): Responses routes are being routed to mongodb instead of typeform
- fix(fetching form): Fetching form by ID returns a single document
- fix(onCreate form): onCreate sets mongo db form id instead of typeform id
Rerouted fetching responses to our backend, this is our last route for the demo and the only thing missing for Issue #78  is updating / deleting forms (but this will be added later).
N/A

[Feat]: Responses routing to our Mongo DB + onCreate Bug Fix + Retrieving Form by Id Refactor

---

server/utilityFunctions/responseParser.js

This PR fixes the issue where individual form responses were being duplicated.
Fix:
- Adds check to ensure that if we have no new responses we do not create an empty responseids document.

Fix: fixes duplicate individual form responses

---

client/components/TopNav/TopNav.module.css

TopNavBar would still show even when modal popped up. Removing z-index solves the problem.
https://github.com/cascaritaco/cascarita/assets/32311654/76855d0c-64e4-4d19-902b-de902c635b4a

fix: adjust z-index for top nav

---

client/components/LanguageDropdown/LanguageDropdown.module.css
client/components/LanguageDropdown/LanguageDropdown.tsx
client/components/LanguagePreferenceButton/LanguagePreferenceButton.tsx
client/components/Modal/Modal.module.css
client/components/TopNav/TopNav.module.css

Although the z-index bug was fixed in #90 , it conflated with showing the `LanguageDropDown` component so that it would not show. That has been corrected. Also timeout was added to the `LanguageDropDown` to stop showing if no activity to select a language was made over the last 5 seconds.
https://github.com/cascaritaco/cascarita/assets/32311654/f74bce89-9a9d-4aac-a5ee-60ca541cfa54

fix: correct z-index to show language options

---

client/components/DragAndDropComponents/DNDCanvas/DNDCanvas.tsx
client/components/DragAndDropComponents/DNDCanvas/types.ts
client/components/DragAndDropComponents/DraggableDropdown/types.ts
client/components/DragAndDropComponents/DraggableEmail/types.ts
client/components/DragAndDropComponents/DraggableLongText/types.ts
client/components/DragAndDropComponents/DraggableMultipleChoice/DraggableMultipleChoice.module.css
client/components/DragAndDropComponents/DraggableMultipleChoice/DraggableMultipleChoice.tsx
client/components/DragAndDropComponents/DraggableMultipleChoice/types.ts
client/i18n/en/components/DraggableFields.json
client/i18n/esp/components/DraggableFields.json

Added ability to multi select choices for multiple choice if checked through the form builder

[Feat]: Added multi selection for form builder

---

client/components/SideNav/SideNav.tsx

Fix for #137. Nav Bar now preserves state when reloading. It will show you the correct corresponding page! See below for fix:

fix: preserving nav state upon reloads

---

server/controllers/user.controller.js

Noticed that `bycrypt` was being used for password generation. All passwords and role handling should go through Auth0 so we should be okay to remove that dependency as needed.
#147

fix: add user by removing password as handled by Auth0

---

client/Dockerfile

Corepack is used in the client and ran in one of the image build steps. This PR ensures that corepack does not use it's default pnpm version but instead use a fixed version. 
This update sets the pnpm version to `9.14.2`
This fixes image builds for the client container.

Fix: Use fixed pnpm version

---

client/src/components/TopNav/TopNav.module.css
client/src/components/TopNav/TopNav.tsx

This PR is to update the user icon and name in the platform's header.
Currently there was a general image hard coded for the user's picture/icon at the top right corner of the platform. With this change the image will be set to the user's custom picture.
We are able to use the user's picture with the use of Auth0. If the user has a picture set for their existing account (e.g. gmail) then Cascarita will show that same picture. If the user does not have a picture set then the image will appear as abbreviations. Screenshots with this example are below. 
[CV-56](https://cascarita.atlassian.net/browse/CV-56?atlOrigin=eyJpIjoiNzU1MmE5MWJmMzZlNDYzOWExZDQxMzIxZjgwZTlmMWYiLCJwIjoiaiJ9)
currently:
updated:

Feat: update user icon and name

---

client/src/components/Page/Page.module.css

Hi, all:
This pull request addresses a bug with the `-webkit-fill-available` attribute which previously extended the web app's width and height beyond the viewport. 
By editing the `width` and `height` properties of the `Page` component, the page is able to load nicely across most browsers.
The screenshot above was taken in Safari, but this was also tested on Firefox, Edge, and Chrome.
[[Bug] Page Component Styles #68](https://github.com/cascarita-io/cascarita/issues/68)

fix: -webkit-fill-available causing responsiveness issues on Safari

---

client/src/components/DragAndDropComponents/DraggablePayment/DraggablePayment.tsx
client/src/components/FormInputComponents/Stripe/StripeComponent.tsx
server/controllers/form.controller.js
server/models/form.js
server/models/formtype.js
server/seeders/20240902193649-demo-stripe-user.js

**Stripe form payment block broken**
- fixed it by using @abanuelo cookie group id solution
**Creating forms is broken  !**
-  FormPayment Table added but column used in the `Forms` table was name 'form_type' on the migration. But models were calling 'form_type_id' so i just made sure the models referencing form type were renamed to `form_type` 
- Since a `form_type` is required, and there is only one default on the database.  I set it as the default value on the controller function where the form is created
1. Go to docker desktop -> click cascarita continer -> open the server container -> go to the `Exec`tab -> run seeder file: `npx sequelize-cli db:seed --seed 20240902193649-demo-stripe-user.js`
3. Creat a form with a payment block, drafggin the payment block should not break form …

Fix/Stripe Payment Component Not Rendering

---

client/src/api/forms/service.ts
client/src/api/forms/types.ts
client/src/api/stripe/service.ts
client/src/components/StripeForm/CheckoutForm.tsx
client/src/pages/FormPage/FormPage.tsx
server/controllers/account.controller.js
server/controllers/form.controller.js
server/controllers/formPayment.controller.js
server/controllers/stripeResources/connectedAccount.controller.js
server/controllers/stripeResources/formTransaction.controller.js
server/migrations/20250217210733-update-form-payment-w-user-stripe-account-id-col.js
server/migrations/20250220024603-update-form-payment-w-response-document-id.js
server/models/formpayment.js
server/models/userstripeaccounts.js
server/routes/webhooks/stripe.webhooks.js

This does a couple of things but over all when a form has a payment block and user fills it out we now keep track of it on our database from when they open the stripe payment element to when they entered their card info and submitted the form ! :
1. webhooks for payment intent events , at the moment only handles when a payment intent is submitted (aka: user provides card info)
2. `formpayment.controller.js `file created with functions to : 
- `createStripeFormPayment()` :  creates `FromPayment` record for a form that has a stripe payment element is rendered
- `connectResponseToFormPayment()` : a function to link `FromPayment` record  to a `Response` record from Mongo  collection
- `updateStripePayment()` : a function that gets used by the webhook to update the status of the stripe payment …

Feature: Handle Stripe Payments

---

server/controllers/stripeResources/connectedAccount.controller.js
server/models/userstripeaccounts.js

Since the addition of `formPayments` table, the association between this new table and this `UserStripeAccounts` was wrong so when webhooks would get used and it updates the record on the `UserStripeAccount` table it would break

Fix: Stripe Account Webhook Broken

---

server/migrations/20250222013628-upgrade-image-column-types.js

Upgrades the datatype for columns in our tables that store image urls. These columns will be used to store S3 image urls. All of these columns existed but they were VARCHAR(255) which is not long enough for S3 urls, specially not if they are signed urls. 
Tables updated:
- Users
- Teams
- TeamHistories
- Players
- PlayerHistories
- Groups
Ticket: [CV-82](https://cascarita.atlassian.net/browse/CV-82?atlOrigin=eyJpIjoiZmMxMmZkODRmYTg3NDcwNzliOGQwMzUxMjAzZGM3YWIiLCJwIjoiaiJ9)
The maximum URL length supported by most web browsers (especially Internet Explorer) is 2083 characters.

upgrade datatype for image url columns

---

client/src/api/stripe/service.ts
client/src/pages/Settings/Payment/Payment.module.css
client/src/pages/Settings/StripeAccountForm/StripeAccountForm.module.css
client/src/pages/Settings/StripeAccountForm/StripeAccountForm.tsx
server/controllers/account.controller.js

Working to plug to the `/api/accounts/connect` to launch the URL to connect a Stripe account

feat: getting connect with stripe connected on FE

---

client/src/App.tsx
client/src/components/Forms/TeamsForm/TeamForm.tsx
client/src/components/GroupProvider/GroupProvider.tsx
client/src/pages/Home/Home.tsx
client/src/pages/Leagues/Leagues.tsx

When users first log in should be able to render Leagues for current group selected immediately:

fix: get group id upon first registration to show leagues

---

client/src/assets/Icons/AcceptIcon.tsx
client/src/assets/Icons/RejectIcon.tsx
client/src/assets/Icons/index.tsx
client/src/components/FormResponses/FormResponses.tsx
client/src/components/Forms/Form.module.css
client/src/components/PaymentCapture/PaymentCapture.tsx
client/src/components/StatusLabel/StatusLabel.module.css
client/src/components/StatusLabel/StatusLabel.tsx

Working to include modal experience when capturing payments. After the action is done, it can not be undone and the success or failure will always show as suggested.
Dropdown icon near status label: https://cascarita.atlassian.net/browse/CV-93
confirmation before and after payment capture: https://cascarita.atlassian.net/browse/CV-87

feat: capture payments modal in form responses

---

client/src/components/Forms/RegistrationTemplateForm/RegistrationTemplateForm.tsx

Adding an option in the registration modal to select who will collect the payment fee

feat: adding who collects fee payment in registration form template modal

---

client/src/pages/NewForm/NewForm.module.css
client/src/pages/NewForm/NewForm.tsx

Adding modal when new form is created to help users understand that a new form has been created
https://github.com/user-attachments/assets/12ee1d1d-d675-411f-9339-4d185b7f1e60
https://cascarita.atlassian.net/browse/CV-92

feat: adding new form created confirmation modal

---

client/src/api/users/query.ts
client/src/api/users/service.ts
client/src/api/users/types.ts
client/src/components/Modal/Modal.module.css
client/src/components/NavBar/NavBar.tsx
client/src/pages/Settings/AccountInfo/AccountInfo.tsx
client/src/pages/Settings/Settings.module.css
server/app.js
server/controllers/user.controller.js
server/routes/user.routes.js

This PR is for the User's Settings page. It includes:
- API endpoint to that returns User and User's Group info
- Front end changes to display the Group code
- Fixes a bug where the NavBar loses its active styling when the user clicks away
Part of [CV-60](https://cascarita.atlassian.net/browse/CV-60)
https://github.com/user-attachments/assets/daad4086-d5c0-40e6-a522-bada8392eda0
- The group code will only be displayed for Staff or Admin Roles. (Subject to change in the future)
- Middleware placement was also updated to catch unhandled errors.
- If a user is not an Admin or Staff, then no Settings information is displayed. Should we populate info from auth0 if they are not admin?

adds api endpoint to return data needed for user settings' page

---

client/src/components/FormResponses/FormResponses.tsx

Bug introduced where selecting on changing the payment status always defaulted to the last row in the form responses table. Now the button can render the accept/rejection/cancel view for the specific row in question.

fix: accept/reject status button for specific indexes

---

client/src/pages/Forms/Forms.tsx

Temporarily disable custom forms by removing the "Create" form button for now.
https://cascarita.atlassian.net/browse/CV-104

fix(temp): disable custom forms

---

client/src/components/FileUpload/FileUpload.tsx
nginx/nginx.conf

Increases the client max body size. 
The default max by nginx is 1mb. We are accepting user images that are up to 8mb large but nginx was only allowing requests that were up to 1mb. So any requests with images that exceeded the default value were being rejected by nginx.
Here the max size is set to 15mb to allow room for larger requests while still setting a reasonable limit.
[CV-103](https://cascarita.atlassian.net/browse/CV-103?atlOrigin=eyJpIjoiMTQxNmEzZmNiYTYyNDZlMGI2ZTQ4M2Y5YzkyODg5MGUiLCJwIjoiaiJ9)

Fix: Increase client max body size

---

client/src/api/leagues/mutations.ts
client/src/api/leagues/query.ts
client/src/api/seasons/query.ts
client/src/components/Forms/LeagueForm/LeagueForm.tsx
client/src/components/Forms/LeagueForm/types.tsx
client/src/components/Forms/SeasonForm/SeasonForm.tsx
client/src/components/Forms/SeasonForm/types.ts
client/src/pages/Leagues/Leagues.tsx
client/src/pages/Seasons/Seasons.tsx
server/controllers/season.controller.js

When you click on "edit" for the season and league modals, it will populate with the existing values
https://cascarita.atlassian.net/browse/CV-107

feat: edit modals populate with existing values for season and leagues modals

---

server/controllers/form.controller.js
server/controllers/formPayment.controller.js

Add functionality to prevent admins from deleting forms when it has form payment responses
[](https://cascarita.atlassian.net/browse/CV-118?atlOrigin=eyJpIjoiNGUwMmU3YzEzM2RhNDE4ZWE1YjExNzNkMDAxOTlmOTAiLCJwIjoiaiJ9)

Prevent Forms from Being Deleted with Payment Responses

---

client/src/api/divisions/query.ts
client/src/api/divisions/service.ts
client/src/api/teams/query.ts
client/src/api/users/mutations.ts
client/src/api/users/query.ts
client/src/api/users/service.ts
client/src/api/users/types.ts
client/src/components/FileUpload/FileUpload.tsx
client/src/components/FileUpload/types.ts
client/src/components/Forms/DivisionForm/DivisionForm.tsx
client/src/components/Forms/DivisionForm/types.ts
client/src/components/Forms/PlayerForm/PlayerForm.tsx
client/src/components/Forms/PlayerForm/schema.ts
client/src/components/Forms/PlayerForm/types.ts
client/src/components/Forms/TeamsForm/TeamForm.tsx
client/src/components/Forms/TeamsForm/types.ts
client/src/components/Forms/UserForm/types.tsx
client/src/components/GroupProvider/GroupProvider.tsx
client/src/pages/Division/Division.tsx
client/src/pages/Players/Players.tsx
client/src/pages/Teams/Teams.tsx

When you click on the edit button for the divisions, teams and player modals, you will have the option to edit the existing values.
https://cascarita.atlassian.net/browse/CV-107

fix: edit modal populate values divisions, teams, and players

---

client/src/components/FormInputComponents/Date/Date.tsx
client/src/components/FormInputComponents/Dropdown/Dropdown.tsx
client/src/components/FormInputComponents/Email/Email.tsx
client/src/components/FormInputComponents/Liability/Liability.tsx
client/src/components/FormInputComponents/LongText/LongText.tsx
client/src/components/FormInputComponents/MultipleChoice/MultipleChoice.tsx
client/src/components/FormInputComponents/PhoneNumber/PhoneNumber.tsx
client/src/components/FormInputComponents/PlayerBlock/PlayerBlock.tsx
client/src/components/FormInputComponents/ShortText/ShortText.tsx
client/src/components/FormInputComponents/Signature/Signature.tsx
client/src/pages/FormPage/FormPage.tsx
client/src/pages/FormPage/schema.ts

This PR fixes a bug where the Responses Form can not be submitted because the validator was not passing. Instead of using zod to validate form, we are using the React Hook Form's own validator to validate.
[Jira Ticket](https://cascarita.atlassian.net/browse/CV-132)

Form page submit bug

---

client/package.json
client/pnpm-lock.yaml
client/src/components/FileUpload/FileUpload.tsx
client/src/components/FormInputComponents/Photo/Photo.tsx
client/src/components/Forms/Form.module.css
client/src/components/Forms/TeamsForm/TeamForm.tsx
client/src/components/Page/Page.module.css
client/src/pages/pages.module.css

Upload now allows for HEIC images and adds react spinner to show loading for images
https://cascarita.atlassian.net/browse/CV-97

fix: HEIC images preview for FileUpload component

---

server/controllers/formPayment.controller.js

When approving a response with a stripe payment, the user was not linked to the `formPayment` entry. The issue was that the `paymentData` was not declared correctly

Fix: Stripe Payment Approval Flow error 

---

server/controllers/formPayment.controller.js

We can filter out formPayments with `response_document_id: null`. When a form is submitted, a `response_document_id` is linked to the corresponding `formPayment`. Therefore, in the Forms/Response view, we should only handle `formPayments` that have a valid `response_document_id`. Currently, the view uses every `formPayment` entry created for the form, regardless of submission status. Which causes responses to have missing status fields on the UI

Feature: Filter out form payments that do not have a response id

---

client/src/index.tsx
server/instrument.js

[As noted in Sentry docs](https://docs.sentry.io/platforms/javascript/configuration/options/#enabled), conditionally rendering the `Sentry.init` call in order to only show Sentry on production

fix: enabling Sentry only for prod

---

server/controllers/user.controller.js

This PR adds the user role(s) information to the data that is returned when users are fetched by a group_id.
[CV-133](https://cascarita.atlassian.net/browse/CV-133?atlOrigin=eyJpIjoiODdiMzIzNzBmOWZmNDE5YmExYmNiY2NiNDlkYTIzY2MiLCJwIjoiaiJ9)
Here are example responses for:
- User with no role assigned (not likely to happen):
```json
{
"id": 14,
"first_name": "Test",
"last_name": "Testing",
"email": "testing3@test.com",
"address": "123 test st",
"date_of_birth":  "2000-12-12",
"phone_number": "1231231234",
"internally_created": null,
"picture": "https://some-url.png",
"UserRoles": []
}
```
- User with one role:
```json
{
"id": 16,
"first_name": "Test",
"last_name": "Test",
"email": "test@test.ca",
"address": "233 asdf st",
"date_of_birth": "2000-12-31",
"phone_number": "1231231234", …
```

feat: add user roles to user list fetched by group_id

---

client/src/components/FormResponses/FormResponses.tsx
client/src/components/FormResponses/helpers.ts
client/src/components/Forms/DeleteForm/DeleteForm.tsx
client/src/components/Forms/Form.module.css
client/src/components/Forms/RegistrationTemplateForm/RegistrationTemplateForm.tsx

This PR introduces a change to the registration template model. A second page was added in order to address a bug where when the content of the model is too large, it overflows outside the modal. 
It also introduces a small UI tweak in the Response Modal where when the player is approved or rejected, instead of showing the expiry time for collecting the payment, it shows the internal status of the payment in Stripe.
[Jira Ticket](https://cascarita.atlassian.net/browse/CV-137)
https://github.com/user-attachments/assets/9032e7cd-ac66-4936-91e5-21babb1f96a5

fix: template register form - two pages

---

server/controllers/stripeEvent.controller.js
server/controllers/stripeResources/formTransaction.controller.js
server/migrations/20250313232855-create-stripe-event.js
server/models/stripeevent.js

1.  migration created for a new table and model, `stripeEvents` . We will use this table to store webhook events. Store the `event_id`, `event_type`, `event_id` , `payload` , `internal_satatus` , `stripe_account_id` , `livemode` (these columns are also indexed on the db to it is easy to query and debug in the future)
2. `stripeEvent.controller.js` file created with a function that handle checking for duplicates , ignoring certain events (at the moment this table is only going to store payment events, we have two webhooks but the other webhook will not receive no where near events as the payment one. The other webhook is the `connectedAccount.controller.js` which handles updates to our users stripe account) and handle retries since stripe will use the same `event.id` (we store that) 
3. …

Feature: Store Stripe Payment Web-hook Events

---

server/controllers/s3.controller.js
server/package-lock.json
server/package.json

This change is to fix image orientation for images included in registration forms.
Uses image's exif metadata to read the image orientation and include that in the final image that is uploaded to S3. 
[CV-157](https://cascarita.atlassian.net/browse/CV-157?atlOrigin=eyJpIjoiMWZhMTNjMTlmMGZmNDVjZWIxMmJkMjk0ZDU3YjUxY2UiLCJwIjoiaiJ9)
Testing our latest release I noticed that some images were being rotated when they were uploaded through a phone. This PR is a fix for that issue.

Fix: keep original image orientation

---

client/src/pages/NewForm/NewForm.tsx

Build is failing, we removed the `Preview Form` button but left the state declaration and the line that sets the `formLink` in `onCreate`
Build is working now

FIX: remove left over form link logic

---

client/src/api/forms/query.ts
client/src/api/forms/service.ts
client/src/api/forms/types.ts
client/src/components/Forms/DeleteForm/types.tsx
client/src/pages/Forms/Forms.tsx

BE returns an `{'error': '...'}` response when a form is flagged as unable to be deleted as it contains form responses. Allowing FE to capture these changes
https://cascarita.atlassian.net/browse/CV-144

fix: properly displaying delete form error messages

---

client/package.json
client/pnpm-lock.yaml
client/src/api/forms/service.ts
client/src/components/Forms/DivisionForm/DivisionForm.tsx
client/src/components/Forms/LeagueForm/LeagueForm.tsx
client/src/components/Forms/SeasonForm/SeasonForm.tsx
client/src/components/Forms/ShareForm/ShareForm.tsx
client/src/components/Forms/TeamsForm/TeamForm.tsx
client/src/components/Layout/Layout.tsx
client/src/pages/Forms/Forms.tsx

This PR introduces a minor change that will allow users to see comfirmation when a form is shared or when a league, seasons, etc is created, edited or deleted. It does using a [Toast](https://www.npmjs.com/package/react-toastify) component.
[Jira Ticket](https://cascarita.atlassian.net/browse/CV-148)
Screen Recording 2025-03-19 at 1.54.17 AM

Feat: Added Toast for confirmation and error messages

---

client/src/components/FormResponses/FormResponses.tsx

Expiry should only show if
- payment is of type `credit card/stripe`
- status is NOT `approved` or `rejected` 
- current date has exceeded the expiry limit
https://cascarita.atlassian.net/browse/CV-164

fix: properly showing expiry

---

client/src/components/FormInputComponents/PlayerBlock/PlayerBlock.tsx

Working to include teams query within player block. This prevents the need to re-create an entire form when new teams are created. See demo below

fix: adding teams query for player block

---

client/src/components/FormResponses/FormResponses.module.css
client/src/components/FormResponses/FormResponses.tsx
client/src/components/FormResponses/types.ts
server/controllers/formPayment.controller.js
server/models/formpayment.js

1. Added a `stripe_url` where it contains the link to the Payment Intent on the connected account's stripe dashboard .
2.  Added the `stripe_url` as a [virtual column](https://sequelize.org/docs/v6/core-concepts/getters-setters-virtuals/#virtual-fields) and used [`get()`](https://sequelize.org/docs/v6/core-concepts/getters-setters-virtuals/#getters) to set up the logic for the creation of the url. Shout out to @garcialuis for pointing me that direction. I think this is a WAY better way of updating query results with attributes we may need ! 
3. I did have to update the query to find the form `id` based of the form document id. For some reason we were using `findAll` but one `document_id` should only be linked to one form `id`.
4. Updated the front end to render a button to redirect users …

Feature: Add Stripe Url for Payment Intents
